FROM ubuntu:20.04

RUN apt update && apt upgrade -y
RUN apt install git python3 python3-pip -y


RUN git clone https://github.com/YulianSalo/diploma.git

###
COPY ./Dockerfile ./diploma

RUN pip install pipreqs

WORKDIR /diploma

RUN pipreqs --encoding utf-8 "./"

RUN pip install -r requirements.txt
